### ISSUE TITLE
Unable to Execute Batch Swap Method

### ISSUE THREAD

**Issue by k3nt0w** [berachain/doc-abis#2]
## Overview
Hello, development team ( @dethebera ) .  I am grateful for the development of such a fantastic product.

I'm attempting to execute various contracts from a server for the development of dapps using Berachain on a trial basis. However, I'm unable to succeed with the `batchSwap` method in [IERC20DexModule.abi.json](https://github.com/berachain/doc-abis/blob/main/PrecompileContracts/IERC20DexModule.abi.json).

The method id becomes `0x5060ffd3` when I generate the Input Data based on the latest [IERC20DexModule.abi.json](https://github.com/berachain/doc-abis/blob/main/PrecompileContracts/IERC20DexModule.abi.json), but when I look at the transaction history using BEX through Metamask, the method id is `0x416daf89`. If the ABI in this repository is outdated, please let me know.

The following implementation is part of an actual implementation using Rust.
In the arguments, I am setting up SwapStep using the response from [https://artio-80085-dex-router.berachain.com/dex/route?quoteAsset=0x7EeCA4205fF31f947EdBd49195a7A88E6A91161B&baseAsset=0x5806E416dA447b267cEA759358cF22Cc41FAE80F&amount=10000000000000000&swap_type=given_in](https://artio-80085-dex-router.berachain.com/dex/route?quoteAsset=0x7EeCA4205fF31f947EdBd49195a7A88E6A91161B&baseAsset=0x5806E416dA447b267cEA759358cF22Cc41FAE80F&amount=10000000000000000&swap_type=given_in).

```rs
const CHAIN_URL: &str = "https://rpc.ankr.com/berachain_testnet";
const CHAIN_ID: u64 = 80085;
const CONTRACT_ADDRESS: &str = "0x0d5862FDbdd12490f9b4De54c236cff63B038074";

pub async fn batch_swap(args: BatchSwapArgs) -> Result<(), InvokeError> {
    let secret = get_secret(&args.wallet_address)?;

    let provider =
        Provider::<Http>::try_from(CHAIN_URL).map_err(|e| InvokeError::from(e.to_string()))?;
    let wallet = secret
        .parse::<LocalWallet>()
        .unwrap()
        .with_chain_id(CHAIN_ID);

    let abi: Abi = serde_json::from_str(include_str!("../../abi/IERC20DexModule.abi.json"))
        .map_err(|e| InvokeError::from(e.to_string()))?;

    let client = SignerMiddleware::new_with_provider_chain(provider, wallet)
        .await
        .map_err(|e| InvokeError::from(e.to_string()))?;

    let client = Arc::new(client);

    let contract = Contract::new(
        CONTRACT_ADDRESS
            .parse::<Address>()
            .map_err(|e| InvokeError::from(e.to_string()))?,
        abi,
        client.clone(),
    );

    let kind = 0u8;
    let deadline: U256 = U256::from(99999999);
    let swaps: Vec<(Address, Address, U256, Address, U256, Bytes)> = args
        .swaps
        .iter()
        .map(|swap| {
            let pool_id = swap
                .pool_id
                .parse::<Address>()
                .map_err(|e| InvokeError::from(e.to_string()))?;
            let asset_in = swap
                .asset_in
                .parse::<Address>()
                .map_err(|e| InvokeError::from(e.to_string()))?;
            let amount_in = U256::from_str_radix(&swap.amount_in.trim_start_matches("0x"), 16)
                .map_err(|e| InvokeError::from(e.to_string()))?;
            let asset_out = swap
                .asset_out
                .parse::<Address>()
                .map_err(|e| InvokeError::from(e.to_string()))?;
            let amount_out = U256::from_str_radix(&swap.amount_out.trim_start_matches("0x"), 16)
                .map_err(|e| InvokeError::from(e.to_string()))?;
            let user_data = Bytes::from(vec![]);

            Ok((
                pool_id, asset_in, amount_in, asset_out, amount_out, user_data,
            ))
        })
        .collect::<Result<Vec<_>, InvokeError>>()
        .unwrap();
    let call = contract
        .method::<_, (Vec<Address>, Vec<U256>)>("batchSwap", (kind, swaps, deadline))
        .map_err(|e| InvokeError::from(e.to_string()))?;

    let tx = call
        .send()
        .await
        .map_err(|e| InvokeError::from(e.to_string()))?;

    let receipt = tx
        .confirmations(1)
        .await
        .map_err(|e| InvokeError::from(e.to_string()))?;
    println!("{:?}", receipt);
    Ok(())
}
```

## Parameters Detail

| Parameter             | Information                                                                                      |
|---------------------|--------------------------------------------------------------------------------------------------|
| Contract Address    | 0x0d5862FDbdd12490f9b4De54c236cff63B038074                                                       |
| ABI                 | IERC20DexModule.abi.json                                                                         |
| Method              | batchSwap                                                                                        |
| Tx History          | [Transaction Link](https://artio.beratrail.io/tx/0x1e740dd756502de0975251a173aa2cdcfa6a6d0a23d25e1ac809760a4949a8cb) |
| Failed Tx method id | 0x5060ffd3                                                                                       |
| Successful Tx method id | 0x416daf89                                                                                   |

If the ABI is up-to-date and there is a mistake in my understanding, I would appreciate it if you could point it out. Thank you.

**Comment by COLONELBIHI** [comment]
I think this is a bug on RouteScan. It's displaying the input data of the last internal call, instead of the original input data submitted by the msg.sender.

**Comment by k3nt0w** [comment]
@COLONELBIHI 
Thank you, we have received similar feedback from the discord community. I ran it with a larger slippage and the Tx succeeded, so I believe it is confirmed to be a RouteScan bug.

I will close this Issue.

**Comment by COLONELBIHI** [comment]
Ah the wild guess
Have a good time swapping.
